name: beloudertv00
favicon: null
layout_spectrum: 0.49621
typography_spectrum: 0.32034
title: Be Louder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b5b4b9'
    - '#636267'
    - '#353c4c'
    - '#989491'
    - '#f7fafd'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
