name: Be Louder
favicon: null
layout_spectrum: 0.8878352788742632
typography_spectrum: 0.7289531517308205
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08421369828283787
  lightness: 0.565581020899117
  saturation: 0.19648183905519545
  rhythmicContrast: 0.5487919566221535
purpose: []
